spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${APPLICATION_DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: pool-datasource
      maximum-pool-size: 50
      minimum-idle: 10
  flyway:
    enabled: true
    locations: classpath:db/migration
    fail-on-missing-locations: false
    baseline-on-migrate: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USER:}
      password: ${REDIS_PASSWORD:}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH_JWK_SET_URI:http://localhost:8080/oauth2/keys}

mybatis-plus:
  global-config:
    db-config:
      table-prefix: ${TABLE_PREFIX:}
  mapper-locations: classpath:/mapper/**/*.xml

# Spring Management Server and Endpoint Config
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env,beans
  server:
    port: 8081
  endpoint:
    health:
      show-details: always

# Spring log config, default logback
logging:
  level:
    root: INFO
    "[org.springframework.web]": INFO
  file:
    name: /var/log/boot/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
