# Data Access Layer config, database/connection pool/verson control/orm
spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT:3306}/${APPLICATION_DATABASE_NAME}?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: ${MYSQL_USER}
        password: ${MYSQL_PASSWORD}
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            pool-name: pool-datasource
            maximum-pool-size: 50
            minimum-idle: 10
    flyway:
        enabled: true
        locations: classpath:db/migration
        fail-on-missing-locations: false
        baseline-on-migrate: true


mybatis-plus:
  global-config:
    db-config:
      table-prefix: ${TABLE_PREFIX:}
  mapper-locations: classpath:/mapper/**/*.xml