# Spring log config, default logback
logging:
  level:
    root: INFO
    '[org.springframework.web]': INFO
  file:
    name: /var/log/boot/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10