name: Dependency Check
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout Code"
              uses: actions/checkout@v2
              
            # - uses: actions/setup-java@v3
            #   with:
            #     distribution: 'temurin'
            #     java-version: '17'
            #     cache: 'maven'

            - name: "Build project with Maven"
              run: mvn clean install
            
            - name: "Dependency Check"
              uses: dependency-check/Dependency-Check_Action@main
              id: Depcheck
              with:
                project: 'basic-framework'
                path: '.'
                format: 'HTML'
                out: 'reports' # this is the default, no need to specify unless you wish to override it
            - name: "Upload Test results"
              uses: actions/upload-artifact@master
              with:
                name: Depcheck report
                path: ${{github.workspace}}/reports
